apiVersion: apps/v1
kind: Deployment
metadata:
  name: rod
  namespace: ramblerutils
  labels:
    app: rod
spec:
  replicas: 3
  template:
    metadata:
      name: rod
      labels:
        app: rod
    spec:
      containers:
        - name: rod
          image: ghcr.io/go-rod/rod
          resources:
            limits:
              memory: "0.6"
              cpu: "0.6"
          ports:
            - containerPort: 7317
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: rod
