apiVersion: v1
kind: Service
metadata:
  namespace: middleware
  name: kafka-service
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  type: NodePort
  ports:
    - port: 9092
      name: kafka-port
      targetPort: 9092
      nodePort: 30092
      protocol: TCP