apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: zookeeper-deployment
      namespace: middleware
    spec:
      selector:
        matchLabels:
          app: zookeeper
      template:
        metadata:
          labels:
            app: zookeeper
        spec:
          containers:
            - name: zookeeper
              image: awesomepayne/zookeeper:v0.1
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "32Mi"
                  cpu: "100m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
              ports:
                - containerPort: 2181

  - apiVersion: v1
    kind: Service
    metadata:
      name: zookeeper-service
      namespace: middleware
      labels:
        app: zookeeper-service
    spec:
      ports:
        - name: zookeeper-port
          port: 2181
          targetPort: 2181
      selector:
        app: zookeeper