apiVersion: apps/v1
kind: Deployment
metadata:
  name: splash
  namespace: ramblerutils
  labels:
    app: splash
spec:
  replicas: 3
  selector:
    matchLabels:
      app: splash
  template:
    metadata:
      labels:
        app: splash
    spec:
      containers:
        - name: splash
          image: scrapinghub/splash:latest
          ports:
            - containerPort: 8050
          resources:
            limits:
              memory: "3Gi"
              cpu: "0.8"
      restartPolicy: Always