apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      namespace: ramblerutils
      labels:
        app: splash
      name: splash
    spec:
      selector:
        app: splash
      ports:
        - port: 8050
          targetPort: 8050
  - apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: splash
      namespace: ramblerutils
      labels:
        name: splash
      annotations:
        kubernetes.io/ingress.class: "nginx"
    spec:
      rules:
        - host: splash.paynewu.com
          http:
            paths:
              - pathType: Prefix
                path: "/"
                backend:
                  service:
                    name: splash
                    port:
                      number: 8050