apiVersion: v1
kind: Service
metadata:
  name: sekiro
  namespace: ramblerutils
spec:
  selector:
    app: sekiro
  type: NodePort
  ports:
    - port: 5600
      nodePort: 30560
    - port: 5601
      nodePort: 30561
    - port: 5602
      nodePort: 30562
    - port: 5603
      nodePort: 30563
