apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-http
  namespace: dev
spec:
  tls:
    - secretName: tls-src # 密钥名字
    - hosts:
        - nginx-test.paynewu.com  # 对应的网站
        - tomcat-test.paynewu.com
  rules:
    - host: nginx-test.paynewu.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
    - host: tomcat-test.paynewu.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: tomcat-service
                port:
                  number: 8080