# namespaces
apiVersion: v1
kind: Namespace
metadata:
  name: nginx_example

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: nginx_example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-cluster
  template:
    metadata:
      labels:
        app: nginx-cluster
    spec:
      containers:
        - name: nginx-cluster
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx_example
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-cluster
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      nodePort: 32761