# services
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: example-nginx
  labels:
    app: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-cluster
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      nodePort: 32761