apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-service-account

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: heketi

rules:
  - apiGroups:
      - ""
    resources:
      -
  - verbs:
      - get
      - list
      - watch

